### ISSUE TITLE
Measurement export command & standalone spacecraft mission

### ISSUE THREAD

**Issue by ChristopherRabotin** [ChristopherRabotin/smd#115]
# Measurements
- [x] Export measurements from N stations
- [x] Define stations with either a reference from built-in stations, or in the `toml` file
# Orbit and Spacecraft
- [x] Define initial orbit and frame in configuration file
- [x] Define spacecraft, dry mass and fuel mass
- [x] Define instantaneous delta-Vs to be done by the spacecraft at given times along with the fuel depletion

# Example
```toml
[spacecraft]
name = "MRO"
fuel = 500
dry = 500

[orbit]
position = [] #[x, y, z]
velocity = [] #[xdot ydot zdot]
body = "Earth"

[error] # To generate datasets only
probability = 0.1 # i.e. 10% of calls to SetState will have an error
position = 1.0 # sigma for Gaussian
velocity = 0.1 # sigma for Gaussian

[perturbations]
J2 = false
J3 = false
J4 = false
bodies = ["Earth", "Moon", "Sun", "Venus", "Jupiter"]

[burns.tcm0]
date = "2015-02-03 15:16:17" # or JDE
deltaV = [1, 2, 3] # in the frame of the spacecraft then

[measurements]
output = "meas.csv"
stations = ["builtin.DSS34", "Other"]

[station.Other]
name = "Other station"
altitude = 100
elevation = 0
latitude = 0
longitude = 0
range_sigma = 0.1
rate_sigma = 0.1
```
